# Generated by Django 5.1.4 on 2025-11-09 12:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TulburTuriinAngilal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ner', models.CharField(max_length=100)),
                ('tailbar', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('ajiltan', 'СӨХ-ийн ажилтан'), ('orshinsuu', 'Оршин суугч')], default='orshinsuu', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Orshinsuu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bair_dugaar', models.CharField(max_length=10)),
                ('utas', models.CharField(max_length=20)),
                ('orshin_baigaa', models.BooleanField(default=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'orshinsuu'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nehemjlel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sar', models.CharField(max_length=20)),
                ('dun', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ognoo', models.DateTimeField(auto_now_add=True)),
                ('tulbur_hiisen', models.BooleanField(default=False)),
                ('ajiltan', models.ForeignKey(limit_choices_to={'role': 'ajiltan'}, on_delete=django.db.models.deletion.CASCADE, related_name='nehemjlel_ilgeesen', to=settings.AUTH_USER_MODEL)),
                ('orshinsuu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nehemjlel_avsan', to='esokhapp.orshinsuu')),
            ],
        ),
        migrations.CreateModel(
            name='Sanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aguulga', models.TextField()),
                ('ognoo', models.DateTimeField(auto_now_add=True)),
                ('harasan', models.BooleanField(default=False)),
                ('orshinsuu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanaluud', to='esokhapp.orshinsuu')),
            ],
        ),
        migrations.CreateModel(
            name='Soh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ner', models.CharField(max_length=200)),
                ('hayg', models.CharField(max_length=300)),
                ('utas', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('uusgesen_ognoo', models.DateTimeField(auto_now_add=True)),
                ('ajiltanuud', models.ManyToManyField(blank=True, limit_choices_to={'role': 'ajiltan'}, related_name='hariyalah_soh', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orshinsuu',
            name='soh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orshinsuud', to='esokhapp.soh'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garchig', models.CharField(max_length=200)),
                ('aguulga', models.TextField()),
                ('ognoo', models.DateTimeField(auto_now_add=True)),
                ('ilgeesen_ajiltan', models.ForeignKey(limit_choices_to={'role': 'ajiltan'}, on_delete=django.db.models.deletion.CASCADE, related_name='ilgeesen_medegdluud', to=settings.AUTH_USER_MODEL)),
                ('soh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medegdluud', to='esokhapp.soh')),
            ],
        ),
        migrations.CreateModel(
            name='Tulbur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sar', models.CharField(max_length=20)),
                ('dun', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tulbur_tulsun', models.BooleanField(default=False)),
                ('tulbur_ognoo', models.DateField(blank=True, null=True)),
                ('tulbur_barimt', models.FileField(blank=True, null=True, upload_to='barimt/')),
                ('orshinsuu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tulburuud', to='esokhapp.orshinsuu')),
                ('tulbur_turul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='esokhapp.tulburturiinangilal')),
            ],
        ),
    ]
